apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: kennydukor/backend-feed:v1
          ports:
            - containerPort: 8080 
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          envFrom:
            - configMapRef:
                name: udacity-proj3-config
            - secretRef:
                name: udacity-proj3-secrets
          volumeMounts:
            - mountPath: "/root/.aws/"
              name: udagram-aws-config
      volumes:
        - name: udagram-aws-config
          configMap:
            name: udagram-aws-config

