version: "1"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:v1
  backend_user:
    build:
      context: ./backend-user
    image: backend-user:v1
  backend_feed:
    build:
      context: ./backend-feed
    image: backend-feed:v1
  frontend:
    build:
      context: ./frontend
    image: frontend:v1