# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yml build --parallel
    - run: docker tag backend-feed:v1 kennydukor/backend-feed:v1
    - run: docker tag backend-user:v1 kennydukor/backend-user:v1
    - run: docker tag frontend:v6 kennydukor/frontend:v6
    - run: docker tag reverseproxy:v1 kennydukor/reverseproxy:v1
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - run: docker push kennydukor/backend-feed:v1
    - run: docker push kennydukor/backend-user:v1
    - run: docker push kennydukor/frontend:v6
    - run: docker push kennydukor/reverseproxy:v1
